const PurchaseStatus = Object.freeze({
    PLACED: "PLACED",
    CONFIRMED: "CONFIRMED",
    PACKAGING_IN_PROGRESS: "PACKAGING_IN_PROGRESS",
    READY_TO_SHIP: "READY_TO_SHIP",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    CANCELLED: "CANCELLED",
    DELIVERED_WITH_PAYMENT_PENDING: "DELIVERED_WITH_PAYMENT_PENDING",
    DELIVERED_WITH_PAYMENT_SUCCESS: "DELIVERED_WITH_PAYMENT_SUCCESS"
})
module.exports = PurchaseStatus;